
- hosts: "{{hosts}}"

  tasks:

    - name: update apt cache
      apt:
        update_cache: yes

    - name: install docker
      apt: name=docker.io

    - name: make sure docker is enabled
      shell: systemctl enable docker # hack for ansible bug

    - name: make sure docker is running
      service:
        state: started
        name: docker

    - name: install apt-transport-https
      apt: name=apt-transport-https

    - name: add kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: update apt cache
      apt:
        update_cache: yes

    - name: swap off
      shell: swapoff -a

    - name: remove swap permanently
      lineinfile:
        dest: /etc/fstab
        state: absent  
        regexp: '^.*swap.*$' 
    
    - name: pass bridged IPv4 traffic to iptables’ chains
      shell: sysctl net.bridge.bridge-nf-call-iptables=1

    - name: install kubelet
      apt: name=kubelet

    - name: install kubeadm
      apt: name=kubeadm

    - name: install kubectl
      apt: name=kubectl

    - name: run kubeadm init
      shell: kubeadm init --apiserver-advertise-address {{hosts}} --pod-network-cidr=192.168.0.0/16

    - name: apply calico network plugin
      shell: kubectl apply -f https://docs.projectcalico.org/v2.6/getting-started/kubernetes/installation/hosted/kubeadm/1.6/calico.yaml

